# features/contexts
version: 2
jobs:
  test-context:
    docker:
      - image: "circleci/clojure:latest"
    steps:
      - run: exit $CONTEXT_SMOKE_TEST_RESULT

workflows:
  version: 2
  my-workflow:
    jobs:
      - test-context:
          context: smoke-test
