# features/workspaces
version: 2.1

jobs:
  workspace-test:
    docker:
      - image: "circleci/clojure:latest"
    working_directory: /tmp
    steps:
      - run: mkdir -p created-workspace
      - run: echo "Hello" > created-workspace/important-data
      - persist_to_workspace:
          root: created-workspace
          paths:
            - important-data
      - attach_workspace:
          at: /tmp/attached-workspace
      - run: |
          if [[ $(cat /tmp/attached-workspace/important-data) == "Hello" ]]; then
            echo "It worked!"
          else
            echo "My important data is missing!"
            exit 1
          fi

workflows:
  version: 2.1
  build:
    jobs:
      - workspace-test
